-- | This module generated by the Quickpull package.
-- Quickpull is available at:
-- <http://www.github.com/massysett/quickpull>

module Decrees where

import Quickpull
import qualified Penny.Lincoln.Natural.Tests

decrees :: [Decree]
decrees =

  [ Decree ( Meta {modDesc = ModDesc {modPath = "lib/Penny/Lincoln/Natural/Tests.hs", modName = ["Penny","Lincoln","Natural","Tests"]}, linenum = 33, qName = "prop_nextPrevGivesSameNumberUnsigned"} ) ( Single Penny.Lincoln.Natural.Tests.prop_nextPrevGivesSameNumberUnsigned )
  , Decree ( Meta {modDesc = ModDesc {modPath = "lib/Penny/Lincoln/Natural/Tests.hs", modName = ["Penny","Lincoln","Natural","Tests"]}, linenum = 36, qName = "prop_nextPrevGivesSameNumberNonZero"} ) ( Single Penny.Lincoln.Natural.Tests.prop_nextPrevGivesSameNumberNonZero )
  , Decree ( Meta {modDesc = ModDesc {modPath = "lib/Penny/Lincoln/Natural/Tests.hs", modName = ["Penny","Lincoln","Natural","Tests"]}, linenum = 43, qName = "prop_addIsAssociativeUnsigned"} ) ( Single Penny.Lincoln.Natural.Tests.prop_addIsAssociativeUnsigned )
  , Decree ( Meta {modDesc = ModDesc {modPath = "lib/Penny/Lincoln/Natural/Tests.hs", modName = ["Penny","Lincoln","Natural","Tests"]}, linenum = 46, qName = "prop_addIsAssociativeNonZero"} ) ( Single Penny.Lincoln.Natural.Tests.prop_addIsAssociativeNonZero )
  , Decree ( Meta {modDesc = ModDesc {modPath = "lib/Penny/Lincoln/Natural/Tests.hs", modName = ["Penny","Lincoln","Natural","Tests"]}, linenum = 56, qName = "prop_multIsAssociativeUnsigned"} ) ( Single Penny.Lincoln.Natural.Tests.prop_multIsAssociativeUnsigned )
  , Decree ( Meta {modDesc = ModDesc {modPath = "lib/Penny/Lincoln/Natural/Tests.hs", modName = ["Penny","Lincoln","Natural","Tests"]}, linenum = 59, qName = "prop_multIsAssociativeNonZero"} ) ( Single Penny.Lincoln.Natural.Tests.prop_multIsAssociativeNonZero )
  , Decree ( Meta {modDesc = ModDesc {modPath = "lib/Penny/Lincoln/Natural/Tests.hs", modName = ["Penny","Lincoln","Natural","Tests"]}, linenum = 62, qName = "prop_monusReturnsValidUnsigned"} ) ( Single Penny.Lincoln.Natural.Tests.prop_monusReturnsValidUnsigned )
  ]
