module Penny.Zinc.Help where

help :: String
help = unlines [
  "usage: zinc [posting filters] report [report options] file . . .",
  "",
  "Posting filters",
  "------------------------------------------",
  "",
  "Dates",
  "-----",
  "",
  "--before",
  "  Posting must be BEFORE this day",
  "--after",
  "  Posting must be AFTER this day",
  "-b, --on-or-before",
  "  Posting must be ON OR BEFORE this day",
  "-a, --on-or-after",
  "  Posting must be ON OR AFTER this day",
  "--day-equals",
  "  Posting must be EXACTLY ON this day",
  "--current",
  "  Same as \"--on-or-before (right now)\"",
  "",
  "Pattern matching",
  "----------------",
  "",
  "-A pattern, --account pattern",
  "  Pattern must match colon-separated account name",
  "--account-level num pat",
  "  Pattern must match sub account at given level",
  "--account-any pat",
  "  Pattern must match sub account at any level",
  "-p pattern, --payee pattern",
  "  Payee must match pattern",
  "-t pattern, --tag pattern",
  "  Tag must match pattern",
  "--number pattern",
  "  Number must match pattern",
  "--flag pattern",
  "  Flag must match pattern",
  "--commodity pattern",
  "  Pattern must match colon-separated commodity name",
  "--commodity-level num pattern",
  "  Pattern must match sub commodity at given level",
  "--commodity-any pattern",
  "  Pattern must match sub commodity at any level",
  "--posting-memo pattern",
  "  Posting memo must match pattern",
  "--transaction-memo pattern",
  "  Transaction memo must match pattern",
  "",
  "Other posting characteristics",
  "-----------------------------",
  "--no-flag",
  "  Posting must not have a flag",
  "--debit",
  "  Entry must be a debit",
  "--credit",
  "  Entry must be a credit",
  "--at-least number",
  "  Entry amount must be greater than or equal to this amount",
  "--less-than number",
  "  Entry amount must be less than this amount",
  "--equals number",
  "  Entry amount must equal this amount",
  "",
  "Options affecting patterns",
  "--------------------------",
  "",
  "-i, --case-insensitive",
  "  Be case insensitive (default)",
  "-I, --case-sensitive",
  "  Be case sensitive",
  "",
  "--within",
  "  Use \"within\" matcher (default)",
  "--pcre",
  "  Use \"pcre\" matcher",
  "--posix",
  "  Use \"posix\" matcher",
  "--exact",
  "  Use \"exact\" matcher",
  "",
  "Sorting",
  "-------",
  "",
  "-s key, --sort key",
  "  Sort postings according to key",
  "",
  "Keys:",
  "  payee, date, flag, number, account, drCr,",
  "  qty, commodity, postingMemo, transactionMemo",
  "",
  "  Ascending order by default; for descending order,",
  "  capitalize the name of the key.",
  "",
  "Operators - from highest to lowest precedence",
  "(all are left associative)",
  "---------------------------------------------",
  "--open expr --close",
  "  Force precedence (as in \"open\" and \"close\" parentheses)",
  "--not expr",
  "  True if expr is false",
  "expr1 --and expr2 ",
  "  True if expr and expr2 are both true",
  "expr1 --or expr2",
  "  True if either expr1 or expr2 is true",
  "",
  "Reports and their options:",
  "",
  "postings, pos",
  "  Show postings in order with a running balance.",
  "  The postings report takes the same options shown",
  "  above; however, these options affect which postings",
  "  are shown in the report. Postings not shown still affect",
  "  the running balance.",
  "",
  "  Additional options:",
  "    --related",
  "      Show related postings",
  "    --head n",
  "      Show only the first n postings",
  "    --tail n",
  "      Show only the last n postings",
  "    --color",
  "      Shade with a bit of color",
  "",
  "balance, bal",
  "  Show a tree of accounts and their balances.",
  "  Options:",
  "    --depth n",
  "      Show accounts only to this depth",
  "    --color",
  "      Shade with a bit of color",
  ""
  ]
