module Penny.Zinc.Help where

help :: String
help = unlines [
  "usage: penny [posting filters] report [report options] file . . .",
  "",
  "Posting filters",
  "------------------------------------------",
  "",
  "Dates",
  "-----",
  "",
  "-b, --beginning",
  "  Posting must be ON or AFTER this day",
  "-e, --ending",
  "  Posting must be BEFORE this day",
  "--current",
  "  Same as \"--ending (tomorrow's date)\"",
  "",
  "Pattern matching",
  "----------------",
  "",
  "-a pattern, --account pattern",
  "  Pattern must match colon-separated account name",
  "--accounts patterns",
  "  Colon-separated account name must match one of many patterns",
  "-p pattern, --payee pattern",
  "  Payee must match pattern",
  "--payees patterns",
  "  Payee must match one of several patterns",
  "-t pattern, --tag pattern",
  "  Tag must match pattern",
  "--tags patterns",
  "  Tag must match one of several patterns",
  "--number pattern",
  "  Number must match pattern",
  "--numbers patterns",
  "  Number must match one of several patterns",
  "--commodity pattern",
  "  Commodity must match pattern",
  "--commodities patterns",
  "  Commodity must match one of several patterns",
  "--level number pattern",
  "  Account name at level n must match pattern",
  "--levels number pattern",
  "  Account name must match one of given level patterns",
  "--posting-memo pattern",
  "  Posting memo must match pattern",
  "--posting-memos patterns",
  "  Posting memo must match one of many patterns",
  "--transaction-memo pattern",
  "  Transaction memo must match pattern",
  "--transaction-memos patterns",
  "  Transaction memo must match one of many patterns",
  "",
  "Other posting characteristics",
  "-----------------------------",
  "--no-flag",
  "  Posting must not have a flag",
  "--flag f",
  "  Posting must have the flag f",
  "--debit",
  "  Entry must be a debit",
  "--credit",
  "  Entry must be a credit",
  "--at-least number",
  "  Entry amount must be at least this amount",
  "--less-than number",
  "  Entry amount must be less than this amount",
  "",
  "Options affecting patterns",
  "--------------------------",
  "",
  "-i, --case-insensitive",
  "  Be case insensitive (default)",
  "-I, --case-sensitive",
  "  Be case sensitive",
  "--invert",
  "  Invert ordinary matching behavior",
  "--no-invert",
  "  Do not invert ordinary matching behavior (default)",
  "",
  "--within",
  "  Use \"within\" matcher (default)",
  "--pcre",
  "  Use \"pcre\" matcher",
  "--posix",
  "  Use \"posix\" matcher",
  "--exact",
  "  Use \"exact\" matcher",
  "",
  "Sorting",
  "-------",
  "",
  "-s key, --sort key",
  "  Sort postings according to key",
  "--multi-sort key1 key2 ...",
  "  Sort postings first by key1, then by key2, etc.",
  "",
  "Keys:",
  "  payee, date, flag, number, account, drcr,",
  "  qty, commodity, postingMemo, transactionMemo",
  "",
  "  Ascending order by default; for descending order,",
  "  capitalize the name of the key.",
  "",
  "Reports and their options:",
  "",
  "register, reg",
  "  Show postings in order with a running balance.",
  "  The register report takes the same options shown",
  "  above; however, these options affect which postings",
  "  are shown in the report. Postings not shown still affect",
  "  the running balance.",
  "",
  "  Additional options:",
  "    --related",
  "      Show related postings",
  "    --head n",
  "      Show only the first n postings",
  "    --tail n",
  "      Show only the last n postings",
  "    --color",
  "      Shade with a bit of color",
  "",
  "balance, bal",
  "  Show a tree of accounts and their balances.",
  "  Options:",
  "    --depth n",
  "      Show accounts only to this depth",
  "    --color",
  "      Shade with a bit of color",
  ""
  ]
