module Penny.Help where

help :: String
help = unlines [
  "usage: penny [options] file . . .",
  "",
  "Options affecting which postings to report",
  "------------------------------------------",
  "",
  "Dates",
  "-----",
  "",
  "-b, --beginning",
  "  Posting must be ON or AFTER this day",
  "-e, --ending",
  "  Posting must be BEFORE this day",
  "--current",
  "  Same as \"--ending (tomorrow's date)\"",
  "",
  "Pattern matching",
  "----------------",
  "-a pattern, --account pattern",
  "  Pattern must match colon-separated account name",
  "--accounts patterns",
  "  Colon-separated account name must match one of many patterns",
  "-p pattern, --payee pattern",
  "  Payee must match pattern",
  "--payees patterns",
  "  Payee must match one of several patterns",
  "-t pattern, --tag pattern",
  "  Tag must match pattern",
  "--tags patterns",
  "  Tag must match one of several patterns",
  "--number pattern",
  "  Number must match pattern",
  "--numbers patterns",
  "  Number must match one of several patterns",
  "--commodity pattern",
  "  Commodity must match pattern",
  "--commodities patterns",
  "  Commodity must match one of several patterns",
  "--level number pattern",
  "  Account name at level n must match pattern",
  "--levels number pattern",
  "  Account name must match one of given level patterns",
  "--posting-memo pattern",
  "  Posting memo must match pattern",
  "--posting-memos patterns",
  "  Posting memo must match one of many patterns",
  "--transaction-memo pattern",
  "  Transaction memo must match pattern",
  "--transaction-memos patterns",
  "  Transaction memo must match one of many patterns",
  "",
  "Other posting characteristics",
  "-----------------------------",
  "--cleared",
  "  Posting must be cleared",
  "--uncleared",
  "  Posting must not be cleared",
  "--debit",
  "  Entry must be a debit",
  "--credit",
  "  Entry must be a credit",
  "--at-least number",
  "  Entry amount must be at least this amount",
  "--less-than number",
  "  Entry amount must be less than this amount",
  "",
  "Options affecting patterns",
  "--------------------------",
  "",
  "-i, --case-insensitive",
  "  Be case insensitive (default)",
  "-I, --case-sensitive",
  "  Be case sensitive",
  "--invert",
  "  Invert ordinary matching behavior",
  "--no-invert",
  "  Do not invert ordinary matching behavior (default)",
  "",
  "--within",
  "  Use \"within\" matcher (default)",
  "--pcre",
  "  Use \"pcre\" matcher",
  "--posix",
  "  Use \"posix\" matcher",
  "--exact",
  "  Use \"exact\" matcher",
  "",
  "Options affecting which transactions to show in the report"
  
  ]
