{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE OverloadedLists #-}
-- | Has a single type that can hold every production from
-- "Penny.Copper.Grammar".  Automatically generated by Pinchot.
module Penny.Copper.Productions where

import Penny.Copper.Grammar
import qualified Penny.Copper.Types as Types

import Pinchot (allRulesRecord)

$(allRulesRecord "Types" allRules)
