{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE OverloadedLists #-}
-- | Functions that take a single value from "Penny.Copper.Types" and
-- return each terminal symbol along with each terminal's location.
-- Automatically generated by Pinchot.
module Penny.Copper.Terminalizers where

import Penny.Copper.Grammar
import qualified Penny.Copper.Types as Types

import Pinchot (terminalizers)

$(terminalizers "Types" allRules)
