{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE OverloadedLists #-}
-- | Functions that take a single value from "Penny.Copper.Types" and
-- return each terminal symbol along with each terminal's location.
-- Automatically generated by Pinchot.
module Penny.Copper.Terminalizers where

import Penny.Copper.Grammar
import qualified Penny.Copper.Types as Types

import Pinchot.Terminalize (terminalizer)

{-
$(terminalizers "Types" allRules)
-}

terminalizer "Types" nilOrBrimRadCom
terminalizer "Types" nilOrBrimRadPer
terminalizer "Types" postingField
terminalizer "Types" rPostingFields
terminalizer "Types" trio
terminalizer "Types" rTopLineFields
terminalizer "Types" nilUngroupedRadPer
terminalizer "Types" brimUngroupedRadPer
terminalizer "Types" rWholeFile
