module Penny.Cabin.Posts.Help where

import qualified Data.Text as X

help :: X.Text
help = X.pack helpStr

helpStr :: String
helpStr = unlines [
  "postings report",
  "Show postings in order with a running balance.",
  "",
  "Posting filters",
  "---------------",
  "These options affect which postings are shown in the report.",
  "Postings not shown still affect the running balance.",
  "",
  "Dates",
  "-----",
  "",
  "--date cmp timespec, -d cmp timespec",
  "  Date must be within the time frame given. timespec",
  "  is a day or a day and a time. Valid values for cmp:",
  "     <, >, <=, >=, ==, /=, !=",
  "--current",
  "  Same as \"--date <= (right now) \"",
  "",
  "Serials",
  "----------------",
  "These options take the form --option cmp num; the given",
  "sequence number must fall within the given range. \"rev\"",
  "in the option name indicates numbering is from end to beginning.",
  "",
  "--globalTransaction, --revGlobalTransaction",
  "  All transactions, after reading the ledger files",
  "--globalPosting, --revGlobalPosting",
  "  All postings, after reading the leder files",
  "--fileTransaction, --revFileTransaction",
  "  Transactions in each ledger file, after reading the files",
  "  (numbering restarts with each file)",
  "--filePosting, --revFilePosting",
  "  Postings in each ledger file, after reading the files",
  "  (numbering restarts with each file)",
  "--filtered, --revFiltered",
  "  All postings, after filters given in the filter",
  "  specification portion of the command line are",
  "  applied",
  "--sorted, --revSorted",
  "  All postings remaining after filtering and after",
  "  postings have been sorted",
  "",
  "Pattern matching",
  "----------------",
  "",
  "-a pattern, --account pattern",
  "  Pattern must match colon-separated account name",
  "--account-level num pat",
  "  Pattern must match sub account at given level",
  "--account-any pat",
  "  Pattern must match sub account at any level",
  "-p pattern, --payee pattern",
  "  Payee must match pattern",
  "-t pattern, --tag pattern",
  "  Tag must match pattern",
  "--number pattern",
  "  Number must match pattern",
  "--flag pattern",
  "  Flag must match pattern",
  "--commodity pattern",
  "  Pattern must match colon-separated commodity name",
  "--posting-memo pattern",
  "  Posting memo must match pattern",
  "--transaction-memo pattern",
  "  Transaction memo must match pattern",
  "",
  "Other posting characteristics",
  "-----------------------------",
  "--debit",
  "  Entry must be a debit",
  "--credit",
  "  Entry must be a credit",
  "--qty cmp number",
  "  Entry quantity must fall within given range",
  "",
  "Operators - from highest to lowest precedence",
  "(all are left associative)",
  "--------------------------",
  "--open expr --close",
  "  Force precedence (as in \"open\" and \"close\" parentheses)",
  "--not expr",
  "  True if expr is false",
  "expr1 --and expr2 ",
  "  True if expr and expr2 are both true",
  "expr1 --or expr2",
  "  True if either expr1 or expr2 is true",
  "",
  "Options affecting patterns",
  "--------------------------",
  "",
  "-i, --case-insensitive",
  "  Be case insensitive (default)",
  "-I, --case-sensitive",
  "  Be case sensitive",
  "",
  "--within",
  "  Use \"within\" matcher (default)",
  "--pcre",
  "  Use \"pcre\" matcher",
  "--posix",
  "  Use \"posix\" matcher",
  "--exact",
  "  Use \"exact\" matcher",
  "",
  "Removing postings after sorting and filtering",
  "---------------------------------------------",
  "--head n",
  "  Keep only the first n postings",
  "--tail n",
  "  Keep only the last n postings",
  "",
  "Other options:",
  "",
  "--width num",
  "  Hint for roughly how wide the report should be in columns",
  "--show field, --hide field",
  "  show or hide this field, where field is one of:",
  "    globalTransaction, revGlobalTransaction,",
  "    globalPosting, revGlobalPosting,",
  "    fileTransaction, revFileTransaction,",
  "    filePosting, revFilePosting,",
  "    filtered, revFiltered,",
  "    sorted, revSorted,",
  "    visible, revVisible,",
  "    lineNum,",
  "    date, flag, number, payee, account,",
  "    postingDrCr, postingCommodity, postingQty,",
  "    totalDrCr, totalCommodity, totalQty,",
  "    tags, memo, filename",
  "--show-all",
  "  Show all fields",
  "--hide-all",
  "  Hide all fields",
  "",
  "--show-zero-balances",
  "  Show balances that are zero",
  "--hide-zero-balances",
  "  Hide balances that are zero",
  ""
  ]
