
-- | Types that group a posting with other interesting information.
--
-- Often in Penny, the user needs to examine postings within a larger
-- context of other postings.  A group of postings has a running
-- balance that you might wish to examine.  Also, sometimes you have a
-- large group of postings, but you only want to examine some of them
-- in detail, while keeping others in the group so that they
-- contribute to the running balance.  Also, you may want to know the
-- ordinal position of a particular posting compared to others.
--
-- The 'Penny.Clatch.Types.Clatch' contains a posting along with a
-- wealth of other information, such as the running balance, the
-- sibling postings, the top line data, and several numbers showing
-- how this posting's position and the position of its transaction
-- relate to other postings and transactions.
--
-- Many other values are created on the way to building a
-- 'Penny.Clatch.Types.Clatch', and all these types are in
-- "Penny.Clatch.Types".
module Penny.Clatch where
